---
- name: create vim symbolic link
  file:
    src: "/Users/{{ ansible_env.USER }}/Dropbox/settings/vim/.vimrc"
    path: "/Users/{{ ansible_env.USER }}/.vimrc"
    state: link

- name: create vim directory symbolic link
  file:
    src: "/Users/{{ ansible_env.USER }}/Dropbox/settings/vim/.vim"
    path: "/Users/{{ ansible_env.USER }}/.vim"
    state: link

- name: create zsh symbolic link
  file:
    src: "/Users/{{ ansible_env.USER }}/Dropbox/settings/zsh/.zshrc"
    path: "/Users/{{ ansible_env.USER }}/.zshrc"
    state: link

- name: create .zsh directory symbolic link
  file:
    src: "/Users/{{ ansible_env.USER }}/Dropbox/settings/zsh"
    path: "/Users/{{ ansible_env.USER }}/.zsh"
    state: link

- name: create .gitignore symbolic link
  file:
    src: "/Users/{{ ansible_env.USER }}/Dropbox/settings/git/.gitignore"
    path: "/Users/{{ ansible_env.USER }}/.gitignore"
    state: link

- name: create .gitconfig symbolic link
  file:
    src: "/Users/{{ ansible_env.USER }}/Dropbox/settings/git/.gitconfig"
    path: "/Users/{{ ansible_env.USER }}/.gitconfig"
    state: link

- name: gather Google JapanseInput directory
  stat:
    path: "/Users/{{ ansible_env.USER }}/Library/ApplicationSupport/Google/JapaneseInput"
  register: japanese_input

- name: if google JapaneseInput directory present, delete it
  file:
    path: "/Users/{{ ansible_env.USER }}/Library/ApplicationSupport/Google/JapaneseInput"
    force: yes
    state: absent
  when: japanese_input.stat.isdir is defined and japanese_input.stat.islnk == False

- name: create google JapaneseInput directory symbolic link
  file:
    src: "/Users/{{ ansible_env.USER }}/Dropbox/settings/JapaneseInput"
    path: "/Users/{{ ansible_env.USER }}/Library/ApplicationSupport/Google/JapaneseInput"
    force: yes
    state: link
