---
- name: finder settings
  command: "defaults write com.apple.finder {{ item.key }} {{ item.value }}"
  with_dict:
    - _FXShowPosixPathInTitle: "{{ _FXShowPosixPathInTitle }}"
    - _FXSortFoldersFirst: "{{ _FXSortFoldersFirst }}"
    - AnimateWindowZoom: "{{ AnimateWindowZoom }}"
    - AppleShowAllFiles: "{{ AppleShowAllFiles }}"
    - AppleShowAllFiles: "{{ AppleShowAllFiles }}"
    - FXDefaultSearchScope: "{{ FXDefaultSearchScope }}"
    - FXEnableExtensionChangeWarning: "{{ FXEnableExtensionChangeWarning }}"
    - FXPreferredViewStyle: "{{ FXPreferredViewStyle }}"
    - QLEnableTextSelection: "{{ QLEnableTextSelection }}"
    - QuitMenuItem: "{{ QuitMenuItem }}"
    - ShowPathbar: "{{ ShowPathbar }}"
    - ShowStatusBar: "{{ FinderShowStatusBar }}"
    - ShowTabView: "{{ ShowTabView }}"
    - WarnOnEmptyTrash: "{{ WarnOnEmptyTrash }}"

- name: dock settings
  command: "defaults write com.apple.dock {{ item.key }} {{ item.value }}"
  with_dict:
    - autohide-delay: "{{ autohide-delay }}"
    - largesize: "{{ largesize }}"
    - magnification: "{{ magnification }}"
    - mcx-expose-disabled: "{{ mcx-expose-disabled }}"
    - tilesize: "{{ tilesize }}"
    - wvous-tl-corner: "{{ wvous-tl-corner }}"

- name: safari settings
  command: "defaults write com.apple.Safari {{ item.key }} {{ item.value }}"
  with_dict:
    - AutoOpenSafeDownloads: "{{ AutoOpenSafeDownloads }}"
    - com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled: "{{ WebKit2DeveloperExtrasEnabled }}"
    - IncludeDevelopMenu: "{{ IncludeDevelopMenu }}"
    - IncludeInternalDebugMenu: "{{ IncludeInternalDebugMenu }}"
    - ShowFullURLInSmartSearchField: "{{ ShowFullURLInSmartSearchField }}"
    - ShowStatusBar: "{{ SafariShowStatusBar }}"
    - SuppressSearchSuggestions: "{{ SuppressSearchSuggestions }}"
    - UniversalSearchEnabled: "{{ UniversalSearchEnabled }}"
    - WebKitDeveloperExtrasEnabledPreferenceKey: "{{ WebKitDeveloperExtrasEnabledPreferenceKey }}"

- name: screen capture settings
  command: "defaults write com.apple.screencapture {{ item.key }} {{ item.value }}"
  with_dict:
    - disable-shadow: "{{ disable-shadow }}"
    - type: "{{ type }}"

- name: terminal settings
  command: "defaults write com.apple.terminal {{ item.key }} {{ item.value }}"
  with_dict:
    - StringEncodings: "{{ StringEncodings }}"

- name: NSGlobalDomain settings
  command: "defaults write NSGlobalDomain {{ item.key }} {{ item.value }}"
  with_dict:
    - AppleShowAllExtensions: "{{ AppleShowAllExtensions }}"
    - AppleShowScrollBars: "{{ AppleShowScrollBars }}"
    - com.apple.springing.delay: "{{ com.apple.springing.delay }}"
    - com.apple.springing.enabled: "{{ com.apple.springing.enabled }}"
    - InitialKeyRepeat: "{{ InitialKeyRepeat }}"
    - KeyRepeat: "{{ KeyRepeat }}"
    - NSWindowResizeTime: "{{ NSWindowResizeTime }}"
    - WebKitDeveloperExtras: "{{ WebKitDeveloperExtras }}"
