---
- homebrew_tap:
    name: homebrew/cask-fonts

- homebrew_cask:
    name: "{{ item }}"
    state: present
    greedy: true
    update_homebrew: true
  loop:
    - 1password
    - amazon-music
    - appcleaner
    - cheatsheet
    - clipy
    - day-o
    - docker
    - dropbox
    - franz
    - google-chrome
    - google-japanese-ime
    - iterm2
    - java
    - jetbrains-toolbox
    - kindle
    - marp
    - ngrok
    - notion
    - ricty
    - slack
    - teensy
    - the-unarchiver
    - vagrant
    - vagrant-manager
    - virtualbox
    - visual-studio-code
    - wunderlist
