---
- homebrew_tap:
    name: homebrew/cask-fonts

- name: install brew cask packages
  homebrew_cask:
    name: "{{ item }}"
    state: upgraded
    greedy: true
    update_homebrew: true
    accept_external_apps: true
  loop:
    - 1password
    - amazon-music
    - appcleaner
    - cheatsheet
    - clipy
    - day-o
    - docker
    - dropbox
    - franz
    - google-chrome
    - google-japanese-ime
    - iterm2
    - java
    - jetbrains-toolbox
    - kindle
    - messenger
    - miro-formerly-realtimeboard
    - ngrok
    - ricty
    - shiftit
    - slack
    - the-unarchiver
    - toggl
    - virtualbox
    - zoom

- name: remove brew cask packages
  homebrew_cask:
    name: "{{ item }}"
    state: absent
    greedy: true
    update_homebrew: true
    accept_external_apps: true
  loop:
    - marp
    - notion
    - teensy
    - vagrant
    - vagrant-manager
    - visual-studio-code
    - wunderlist
