---
- homebrew:
    name: "{{ item }}"
    state: latest
    update_homebrew: true
  loop:
    - autoconf
    - awscli
    - docker
    - docker-compose
    - gettext
    - ghq
    - git
    - graphviz
    - gzip
    - imagemagick
    - jq
    - maven
    - mecab
    - mecab-ipadic
    - ncurses
    - nkf
    - nvm
    - openssl
    - pcre
    - pcre2
    - peco
    - pkg-config
    - pyenv
    - q
    - readline
    - ruby-build
    - tig
    - yarn
    - yarn-completion
    - zlib
    - zsh
    - zsh-completions
